#! /usr/bin/env python
import os

os.chdir("/home/ubuntu/practice/git/algorithms_and_ds_playground")
os.system("git pull origin master 2>&1 | tee ~/temp/outputfile.txt")
os.system("git add -A | tee ~/temp/outputfile.txt")
os.system("git commit -m 'Day-61 One DP problem and finished chap 2 of CTCI'2>&1 | tee ~/temp/outputfile.txt")
os.system("git push origin master 2>&1 | tee ~/temp/outputfile.txt")
print("\n\n\nPushed to Git hopefully. Here's a status:\n\n\n")
os.system("mutt -s 'day-61 details'  ravi.mandliya@gmail.com < ~/temp/outputfile.txt")


